// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type TbUser struct {
	UsrID            uint32
	UsrEmail         string
	UsrPhone         string
	UsrUsername      string
	UsrPassword      string
	UsrCreatedAt     int32
	UsrUpdatedAt     int32
	UsrCreateIpAt    string
	UsrLastLoginAt   int32
	UsrLastLoginIpAt string
	UsrLoginTimes    int32
	// Status 1: enabled, 0: disabled, -1: deleted
	UsrStatus bool
}
